### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by DrTableBasse** [robinelfrink/gs1200-exporter#116]
Hello ! 

Do you have any dashboard or do you need one ? 

If you need it, I'll work on it and do a PR if you want 😄

**Comment by DrTableBasse** [comment]
OK thx ! btw i would like to have your dashboard too even if it's not a share-with-the-world quality as you said 😄 

I'll do a PR when I'll finish the dashboard, thx !

**Comment by robinelfrink** [comment]
Please leave this issue open so others can see that a dashboard is being worked on.

Attached is my dashboard.
[Zyxel GS1200-1716975912155.json](https://github.com/robinelfrink/gs1200-exporter/files/15482420/Zyxel.GS1200-1716975912155.json)

**Comment by DrTableBasse** [comment]
yes sorry ! 

For me it's a pretty good dashboard you make. I really apprecited it and discover some tips and tricks 😄 (I'm new with grafana)
I think you can publish it on grafana directly
