### ISSUE TITLE
Add poe stats

### ISSUE THREAD

**Issue by ludoo** [robinelfrink/gs1200-exporter#140]
This is really nice, thanks for releasing it! Could you possibly integrate PoE data the switch exposes at `/poe_data.js`?

**Comment by robinelfrink** [comment]
I could, but my switch doesn't do PoE. Can you show me the contents of the file?

**Comment by ludoo** [comment]
Absolutely, here is the response:

```javascript
var total_power = 60;
var max_led_power = 50;
var port_power =[ 4.9,5.7,6.1,0];
 var total_real_power = 16.8;
 ```

**Comment by robinelfrink** [comment]
Thanks. Any idea what unit these values are in? For the `port-power`-list, what ports would these values refer to?

**Comment by robinelfrink** [comment]
Also, it'd be cool if you would share your model, so I can add some kind of compatibility-list.

**Comment by ludoo** [comment]
Here it is: `GS1200-5HP v2`.

**Comment by robinelfrink** [comment]
@ludoo Can you test the test-build from #146 ?
* Container: https://github.com/robinelfrink/gs1200-exporter/pkgs/container/gs1200-exporter
* Binaries: https://github.com/robinelfrink/gs1200-exporter/actions/runs/12051248239#artifacts

**Comment by robinelfrink** [comment]
@ludoo Can you check the build from #146 ?
* Binaries: https://github.com/robinelfrink/gs1200-exporter/actions/runs/12051486372#artifacts
* Container: https://github.com/robinelfrink/gs1200-exporter/pkgs/container/gs1200-exporter/313086683?tag=test

**Comment by ludoo** [comment]
Oh wow, you managed to do it! Will test as soon as I'm out of meetings, thanks a lot for this!

**Comment by ludoo** [comment]
Seems to work beautifully

![image](https://github.com/user-attachments/assets/d1e44bc7-6705-4935-86a8-a09f8b046159)

**Comment by robinelfrink** [comment]
Cool, thanks for the feedback. Can you show the `max_power` metrics as well?

I'm going to let this version run for a day and merge if it doesn't crash :)

**Comment by ludoo** [comment]
Here it is

![image](https://github.com/user-attachments/assets/5c32ad1c-ec9e-4bc1-a47d-a81ca2ecc8cb)
