### ISSUE TITLE
link_data.js tx/rx stats itemized

### ISSUE THREAD

**Issue by meeowgler** [robinelfrink/gs1200-exporter#49]
Rather than using the sum of Zyxel's multiple array values for tx/rx, were you able to determine if there's meaning to the multiple values? For instance, whether one of them is error packets? I agree that they have a really weird way of reporting stats. There has to be some meaning to this weirdness.

**Comment by robinelfrink** [comment]
I can only guess from what the UI says: **StatusTX(Pkts)** and **RX(Pkts)**. Which says nothing about throughput or errors, only packet rate.
