### ISSUE TITLE
Assistance Needed with Docker Error Logs

### ISSUE THREAD

**Issue by A-Void-Me** [robinelfrink/gs1200-exporter#85]
Hi, apologies for reaching out, but I've been encountering some unexpected error logs since December. The logs look like this:

```
root@Exporter:~# docker logs gs1200-exporter 
time="2024-01-18T22:44:07+01:00" level=info msg="Listening for requests on port 9934"
time="2024-01-18T22:44:07+01:00" level=error msg="Collect error: (anonymous): Line 1:1 Unexpected token < (and 10 more errors)"
time="2024-01-18T22:45:07+01:00" level=error msg="Collect error: (anonymous): Line 1:1 Unexpected token < (and 10 more errors)"
time="2024-01-18T22:46:07+01:00" level=error msg="Collect error: (anonymous): Line 1:1 Unexpected token < (and 10 more errors)"
```

Despite upgrading from version V2.00(ABME.2)C0 to V2.00(ABME.3)C0 today, the issue persists. I'm having trouble pinpointing the cause. Do you have any suggestions on changes I might need to make on my end to resolve this?

Thanks for your assistance.

**Comment by robinelfrink** [comment]
Now that's a very unhelpful message.

I just released v2.7.5 which shows more logging when using `-verbose`. Can you paste output using this version?

Also, please login in your GS1200's webinterface, fetch the following files, and paste the (anonymized) contents?

* `http://<ip-address>/system_data.js`
* `http://<ip-address>/link_data.js`
* `http://<ip-address>/VLAN_1Q_List_data.js`

**Comment by A-Void-Me** [comment]
I played around with my system and used a new switch to check the firmware (ABME.2). It seems that, somehow, my firmware got corrupted or "bricked." When I looked at the Prometheus data, I couldn't find the information from link_data.js.

The new firmware version V2.00(ABME.3)C0 appears to be the latest, but there might be errors associated with it as well. (Not tested by you yet)

logs running with -verbose:
`compose.cli.verbose_proxy.proxy_callable: docker events <- (filters={'label': ['com.docker.compose.project=root', 'com.docker.compose.oneoff=False']}, decode=True)
compose.cli.verbose_proxy.proxy_callable: docker events -> <docker.types.daemon.CancellableStream object at 0x7f2c62096f10>
gs1200-exporter            | time="2024-01-19T12:23:45+01:00" level=info msg="Listening for requests on port 9934"
gs1200-exporter            | time="2024-01-19T12:24:07+01:00" level=error msg="Collect error: (anonymous): Line 1:1 Unexpected token < (and 10 more errors)"
`
system_data.js:
`
var Max_port = '8';
var model_name = 'GS1200-8';
var sys_dev_name = 'XX';
var sys_fmw_ver = 'V2.00(ABME.2)C0';
var sys_bld_date = '2021.12.17';
var sys_MAC = 'XX';
var sys_IP = 'XX';
var sys_sbnt_msk = 'XX';
var sys_gateway = 'XX';
var sys_dhcp_state = '0';
var sys_first_login = '0';
var system_uptime = '30';
var loop = 'Normal';
var loop_status = ['Normal','Normal','Normal','Normal','Normal','Normal','Normal','Normal','Loop','Loop','Loop',];
var logined = '1';
var isTrunk0 = 0;
var isTrunk1 = 0;
var sys_eee_state = '1';
var sys_led_state = '0';
var http_timeout_time = '5';
`
link_data.js:
`
var portstatus = ['Up','Up','Up','Down','Down','Up','Down','Up'];
var speed = ['1000 Mbps Full','1000 Mbps Full','1000 Mbps Full','0 Mbps','0 Mbps','100 Mbps Full','0 Mbps','1000 Mbps Full'];
var Stats = [
['65432',26918,0,0,'256','65432',101925,0,0,'256',0],
['65432',4954,0,0,'256','65432',2742,0,0,'256',0],
['65432',6904,0,0,'256','65432',5643,0,0,'256',0],
['65432',0,0,0,'256','65432',0,0,0,'256',0],
['65432',0,0,0,'256','65432',0,0,0,'256',0],
['65432',1642,0,0,'256','65432',0,0,0,'256',0],
['65432',0,0,0,'256','65432',0,0,0,'256',0],
['65432',101062,0,0,'256','65432',25519,0,0,'256',0]];`

VLAN_1Q_List_data.js:
`
var isTrunkGroupOne = 0;
var isTrunkGroupTwo = 0;
var pvids = [XX];
var port_nums = 8;
var qvlans = [
[XX']
];
`

**Comment by robinelfrink** [comment]
> I played around with my system and used a new switch to check the firmware (ABME.2). It seems that, somehow, my firmware got corrupted or "bricked." When I looked at the Prometheus data, I couldn't find the information from link_data.js.

Are you saying that with the new switch the exporter works fine?

I'll test against the new firmware soon and create a seperate issue for that if needed.

**Comment by A-Void-Me** [comment]
Yeah, something was off on my end. I had to do a factory reset and go back to ABME.1 for some reason.

Thanks for your help and support!
